apiVersion: v1
kind: Pod
metadata:
        name: eeg-ssl
spec:
        restartPolicy: Never
        volumes:
               - name: scratch
                 emptyDir: {}
               - name: ceph
                 hostPath:
                        path: /home/dtyoung
                        type: Directory
        containers:
                - name: eeg-ssl-container
                  image: dtyoung/eeg-ssl:voyager
                  volumeMounts:
                         - mountPath: /scratch
                           name: scratch
                         - mountPath: /ceph
                           name: ceph
                  resources:
                         limits:
                                memory: 128G
                                cpu: 32
                                habana.ai/gaudi: 4
                                hugepages-2Mi: 95000Mi
                         requests:
                                memory: 128G
                                cpu: 32
                                habana.ai/gaudi: 4
                                hugepages-2Mi: 95000Mi
                  env:
                    - name: checkpt
                      value: "/ceph/datasets/stable_diff/checkpoint_trained_habana"
                    - name: output
                      value: "/ceph/results/stable_diffusion/inference_from_trained_habana"
                  command: ["/bin/sh", "-c"]
                  # Just spin & wait forever
                  command: [ "/bin/bash", "-c", "--" ]
                  args: [ "while true; do sleep 30; done;" ]
