# lightning.pytorch==2.5.0
seed_everything: null
trainer:
  deterministic: false
  accelerator: auto
  strategy: auto
  devices: auto
  num_nodes: 1
  precision: null
  logger:
    # class_path: lightning.pytorch.loggers.WandbLogger
    class_path: lightning.pytorch.loggers.TensorBoardLogger
    init_args:
      name: null
      save_dir: lightning_logs
      # save_dir: .
      # version: null
      # offline: false
      # dir: null
      # id: null
      # anonymous: null
      # project: eeg-ssl
      # log_model: true
      # experiment: null
      # prefix: ''
      # checkpoint_name: null
      # entity: null
      # notes: null
      # tags: null
      # config: null
      # config_exclude_keys: null
      # config_include_keys: null
      # allow_val_change: true
      # group: null
      # job_type: "training"
      # mode: online
      # force: null
      # reinit: null
      # resume: "allow"
      # resume_from: null
      # fork_from: null
      # save_code: true
      # tensorboard: null
      # sync_tensorboard: null
      # monitor_gym: null
      # settings: null
  # callbacks:
  #   class_path: lightning.pytorch.callbacks.ModelCheckpoint
  #   init_args:
  #     monitor: val_Classifier/accuracy
  #     mode: max
  #     save_top_k: 2
  #     save_last: true
  #     every_n_train_steps: 50
  #     save_weights_only: false
  #     auto_insert_metric_name: true
  #     filename: "{epoch:03d}-{val_Classifier_accuracy:.3f}"
  fast_dev_run: false
  max_epochs: 10
  min_epochs: null
  max_steps: -1
  min_steps: null
  max_time: null
  limit_train_batches: null
  limit_val_batches: null
  limit_test_batches: null
  limit_predict_batches: null
  overfit_batches: 0.0
  val_check_interval: null
  check_val_every_n_epoch: 3
  num_sanity_val_steps: null
  log_every_n_steps: 1
  enable_checkpointing: True
  enable_progress_bar: null
  enable_model_summary: null
  accumulate_grad_batches: 1
  gradient_clip_val: null
  gradient_clip_algorithm: null
  deterministic: null
  benchmark: null
  inference_mode: true
  use_distributed_sampler: true
  profiler: null
  detect_anomaly: false
  barebones: false
  plugins: null
  sync_batchnorm: false
  reload_dataloaders_every_n_epochs: 0
  default_root_dir: .
model:
  class_path: libs.ssl_task.Classification.ClassificationLit
  init_args:
    encoder:
      class_path: braindecode.models.ShallowFBCSPNet
      init_args:
        n_outputs: 2
        n_chans: 129
        n_times: 500
    encoder_emb_size: 1024
    emb_size: 100
    dropout: 0.1
data:
  ssl_task:
      class_path: libs.ssl_task.Classification
  window_len_s: 2
  batch_size: 32
  num_workers: 0
  data_dir: /mnt/nemar/openneuro
  cache_dir: data
  datasets:
  # - ds005505
  # - ds005506
  # - ds005507
  # - ds005508
  # - ds005509
  # - ds005510
  # - ds005511
  # - ds005512
  # - ds005514
  # - ds005515
  - ds005510
  target_label: sex
  overwrite_preprocessed: false
  mapping: 
    M: 0
    F: 1
  val_release: ds005510
optimizer: null
lr_scheduler: null
ckpt_path: null
