# syntax=docker/dockerfile:1.7
# Base image
FROM vault.habana.ai/gaudi-docker/1.15.1/ubuntu22.04/habanalabs/pytorch-installer-2.2.0:latest

# Install dependencies  
RUN pip3 install --no-cache-dir \
    numpy==1.26.4 \
    git+https://github.com/dungscout96/mne-python.git \
    git+https://github.com/braindecode/braindecode.git \
    tensorboard \
    lightning==2.5.0 \
    "lightning[pytorch-extra]" \
    torchmetrics==1.6.1 \
    wandb \
    litserve \
    mne-bids

RUN pip3 install --ignore-installed \
    torchvision \
    torchaudio

# Run hl-smi as an initial command and specify the script
CMD ["hl-smi"]
